gin:
  mode: debug
  port: 8080
gorm:
  datasource:
    ddl: NONE
    host: "localhost:3306"
    protocol: "tcp"
    schema: "restapi"
    user: "root"
    password: "test"
    maxIdleConn: 10
    maxOpenConn: 10
    charset: "utf8"
    parseTime: true
    loc: "Local"
  gormConfig:
    DisableForeignKeyConstraintWhenMigrating: true
    SkipDefaultTransaction: true
swagger:
  use: true
  routerPath: "/docs/*any"